name: deploy flask app

on:
  push:
    branches:
      - develop
      - master
      - main
  pull_request:
    branches:
      - master
      - main


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
      - name: Deploy to the specified server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /data/block_onchain
            echo 'source code'
            git pull
            git checkout $branches
            python3 -m venv venv
            source ./venv/bin/activate
            pip install -r requirements.txt
            nohup python3 manager.py >> app.out 2>&1 &
